# Generated by Django 5.0.4 on 2024-05-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.CharField(max_length=30, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_from',
            field=models.DateField(verbose_name='Fecha Inicial'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_to',
            field=models.DateField(verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('doing', 'Doing'), ('completed', 'Completed')], default='backlog', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Titulo'),
        ),
    ]
