# Generated by Django 5.0.4 on 2024-05-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_task_customer_alter_task_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('doing', 'Doing'), ('done', 'Done')], default='backlog', max_length=20, verbose_name='Estado'),
        ),
    ]
